CREATE TABLE usuarios(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	dni VARCHAR(9) UNIQUE NOT NULL,
	nombre VARCHAR(100) NOT NULL,
	email VARCHAR(150) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	rol VARCHAR(20) NOT NULL
);

CREATE TABLE relojs (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	nombre VARCHAR(200) NOT NULL,
	modelo VARCHAR(150),
	descripcion VARCHAR(500),
	stock INT, 
	precio INT CHECK (precio < 0)
);

CREATE TABLE compras (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	id_usuario INT NOT NULL,
	id_reloj INT NOT NULL,
	fecha_compra TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT fk_compras_usuario
		FOREIGN KEY (id_usuario)
		REFERENCES usuarios(id)
		ON DELETE CASCADE,

	CONSTRAINT fk_compras_reloj
		FOREIGN KEY (id_reloj)
		REFERENCES relojs(id)
		ON DELETE CASCADE
);